name: Shell commands on self hosted server

on: [push]

jobs:
  run-shell-command:
    runs-on: self-hosted
    steps:
      - name: echo a string
        run: |
          echo "Hello World!"
          hostname
          whoami
          pwd
